<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Agile Engineering\Projects\MockFakeStubExamples\NunitProject.nunit" total="1" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2011-10-07" time="09:43:26">
  <environment nunit-version="2.5.10.11092" clr-version="2.0.50727.3053" os-version="Microsoft Windows NT 5.1.2600 Service Pack 3" platform="Win32NT" cwd="C:\Agile Engineering\Projects\MockFakeStubExamples\MockFakeStubExamples\bin\Release" machine-name="KEVIN-5A260E04F" user="Administrator" user-domain="KEVIN-5A260E04F" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Project" name="C:\Agile Engineering\Projects\MockFakeStubExamples\NunitProject.nunit" executed="True" result="Failure" success="False" time="0.063" asserts="0">
    <results>
      <test-suite type="Assembly" name="C:\Agile Engineering\Projects\MockFakeStubExamples\MockFakeStubExamples\bin\Release\MockFakeStubExamples.dll" executed="True" result="Failure" success="False" time="0.063" asserts="0">
        <results>
          <test-suite type="Namespace" name="AgileEngineering" executed="True" result="Failure" success="False" time="0.063" asserts="0">
            <results>
              <test-suite type="TestFixture" name="FacadeTest" executed="True" result="Failure" success="False" time="0.047" asserts="0">
                <results>
                  <test-case name="AgileEngineering.FacadeTest.exampleTest" executed="True" result="Failure" success="False" time="0.031" asserts="7">
                    <failure>
                      <message><![CDATA[  Expected: 42
  But was:  65
]]></message>
                      <stack-trace><![CDATA[
Server stack trace:
at NUnit.Mocks.MockCall.Call(Object[] actualArgs)
at NUnit.Mocks.MockMethod.Call(Object[] args)
at NUnit.Mocks.Mock.Call(String methodName, Object[] args)
at NUnit.Mocks.MockInterfaceHandler.Invoke(IMessage msg)

Exception rethrown at [0]:
at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
at AgileEngineering.ICreditCardService.CommitTransaction(Int32 transactionId)
at AgileEngineering.AccountUpdateFacade.renewAccount(String accountId, String creditCardNumber) in C:\Agile Engineering\Projects\MockFakeStubExamples\MockFakeStubExamples\FacadeExample.cs:line 44
at AgileEngineering.FacadeTest.exampleTest() in C:\Agile Engineering\Projects\MockFakeStubExamples\MockFakeStubExamples\FacadeTest.cs:line 27
]]></stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>